[package]
name = "pg-peek"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "pgpk"
path = "src/main.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pg-peek-lib = { path = "../pg-peek-lib" }

